name: UEA Streamlit Keeper

on:
  schedule:
    # Corre todos os dias às 10:14 UTC (06:14 AM Horário de Manaus)
    # Alterado de :00 para :14 para evitar congestionamento nos servidores
    - cron: '14 10 * * *'
  workflow_dispatch:

# 🔑 LIBERA PERMISSÃO DE ESCRITA PARA O KEEPALIVE FUNCIONAR
permissions:
  actions: write
  contents: write

jobs:
  rpa_wake_up:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar o repositório atual
      uses: actions/checkout@v4.2.2

    - name: 🐍 Configurar o ambiente Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.11'

    - name: 📦 Instalar dependências básicas
      run: |
        python -m pip install --upgrade pip
        pip install playwright

    - name: 🌐 Instalar o Navegador Chromium e dependências do sistema
      run: playwright install chromium --with-deps

    - name: 🤖 Executar o Script RPA
      run: python wake_up.py
      
 #   - name: 🛡️ Prevenir suspensão do Cron (Keepalive)
 #    uses: gautamkrishnar/keepalive-workflow@v2
